### DISCUSSION TITLE
More results for recently added movies/episodes.

### DISCUSSION THREAD

**Discussion by Litcube** [boralyl/kodi-recently-added#15] [Q&A]
I've tried fiddling with the options in the card, such as number of movies, but I can only seem to get the card to display 5 at a time of each.

![image](https://github.com/user-attachments/assets/7aee4fac-defc-47eb-98a1-0f4e2ed05b88)

![image](https://github.com/user-attachments/assets/fcf584e7-7a61-4eaa-baa4-a88b409c442a)

**Comment by boralyl** [comment]
Use the `max` key to change from the default limit of `5`.  e.g.

```yaml
type: custom:upcoming-media-card
entity: sensor.kms_m_01jh4rcc4anxtvtthtbcgaq0m8
max: 10
show_thumbnail: true
```

https://github.com/custom-cards/upcoming-media-card/tree/master?tab=readme-ov-file#main-config
